# Site settings
title: Teja Vemparala
email: vemparalateja18+blog@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
linkedin_username: teja-vemparala-38411111b

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: auto
  social_links:
    twitter: your_twitter_username
    github: tejavemparala
    linkedin: your_linkedin_username

# Show excerpts on the homepage
show_excerpts: true

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
