# Site settings
title: Teja Vemparala
email: tejavemparala@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog where I share thoughts on technology, programming, 
  and life lessons. Join me on this journey of continuous learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tejavemparala.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_username
github_username: tejavemparala
linkedin_username: your_linkedin_username

# Author information
author:
  name: Teja Vemparala
  email: your-email@example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: auto
  social_links:
    twitter: your_twitter_username
    github: tejavemparala
    linkedin: your_linkedin_username

# Show excerpts on the homepage
show_excerpts: true

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
